"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[directory]
truncation_length = 6
truncate_to_repo = false


################################################################################
## removing all unnecessary packages
################################################################################

[package]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[buf]
disabled = true

[nodejs]
disabled = true

[golang]
disabled = true

[git_commit]
disabled = true

[git_status]
disabled = true

[battery]
disabled = true

[docker_context]
disabled = true

[rust]
disabled = true


################################################################################
## custom package configs
################################################################################

[kubernetes]
disabled = false
symbol = "⎈"
format = '\([$symbol](blue bold)|[$context](red bold)(:[$namespace](cyan bold))\) '

[git_state]
disabled = false

[git_branch]
disabled = false
format = '[\[$symbol$branch(:$remote_branch)\]](green bold) '

[python]
disabled = false
